# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firts_name',
            field=models.CharField(default=' ', max_length=15, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=' ', max_length=20, verbose_name='Apellido'),
            preserve_default=False,
        ),
    ]
