# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 5, 40, 2, 450343, tzinfo=utc), verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
    ]
