# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 3, 23, 36, 111987, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
