# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20161006_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='entry',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='entry',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='michel', max_length=100, verbose_name='Autor del comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(default='blank', verbose_name='Contenido del comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='titulo', max_length=100, verbose_name='Titulo del post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
