# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 15:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20161009_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
