# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('Blog', '0008_auto_20161015_1519'),
	]
	
	operations = [
		migrations.AddField(
			model_name='post',
			name='post_description',
			field=models.CharField(default='Descripcion', max_length=500, verbose_name='Descripción'),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='post',
			name='post_img',
			field=models.CharField(default='None', max_length=100, verbose_name='Imagen principal'),
			preserve_default=False,
		),
	]
