# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 20:30
from __future__ import unicode_literals

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('taggit', '0002_auto_20150616_2121'),
		('Blog', '0009_auto_20161015_1950'),
	]
	
	operations = [
		migrations.AddField(
			model_name='post',
			name='post_tags',
			field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
			                                      through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
		),
	]
