# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('Blog', '0010_post_post_tags'),
	]
	
	operations = [
		migrations.AddField(
			model_name='comment',
			name='comment_title',
			field=models.TextField(default='nada', verbose_name='Titulo del comentario'),
			preserve_default=False,
		),
	]
