# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('Blog', '0011_comment_comment_title'),
	]
	
	operations = [
		migrations.AlterField(
			model_name='comment',
			name='comment_title',
			field=models.CharField(max_length=50, verbose_name='Titulo del comentario'),
		),
	]
