# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('Blog', '0012_auto_20161018_2233'),
	]
	
	operations = [
		migrations.RemoveField(
			model_name='comment',
			name='comment_title',
		),
	]
